# Use an official Node.js runtime as a base image
FROM node:20-alpine as prod

# Set the NODE_ENV environment variable to production
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

# Set the working directory to /usr/src/app
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install only production dependencies
RUN npm i --only=production

# Remove the package.json file to reduce image size
RUN rm -f package.json


