# Use an official Node.js runtime as a base image
FROM node:20.11.1 as base

# Set the working directory to /usr/src/app
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install any needed packages specified in package.json
RUN npm install

# Install the rimraf package globally
RUN npm i -g rimraf

# Remove the package.json file to reduce image size
RUN rm -f package.json